name: build
on: [push]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip
    - name: Install dependencies
      run: |
        pip install -e .
        pip install pytest
    - name: Test with pytest
      run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)/src
          pytest
    - name: Build package distribution
      if: startsWith(github.ref, 'refs/tags')
      run: |
        python -m pip install build 
        python -m build --sdist --wheel --outdir dist/ .
    - name: Publish package distribution to PyPI
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        skip_existing: true
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}